#!/usr/bin/env python3
# Copyright © 2015-20 Qtrac Ltd. All rights reserved.

import os
import random
import sys
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
import unittest

import Saf
import SortAs


DEBUG = 0


class TestSortAs(unittest.TestCase):

    def setUp(self):
        pass # self.maxDiff = None


    # Word by Word (NISO TR 3)
    def test_wordByWordNISO3(self):
        items = EXPECTED_BY_WORD[:]
        random.shuffle(items)
        results = []
        for term, saf, sortas in items:
            if saf != Saf.CUSTOM:
                sortas = SortAs.wordByWordNISO3(term, saf, pad_digits=4)
            results.append((sortas, term, saf))
        results.sort()
        for i in range(len(EXPECTED_BY_WORD)):
            sortas, aterm, asaf = results[i]
            xterm, xsaf = EXPECTED_BY_WORD[i][:2]
            if DEBUG == 1:
                print("{:35} → {:35} : {}".format(aterm, sortas, xterm))
            self.assertEqual(aterm, xterm)
            self.assertEqual(asaf, xsaf)


    # Letter by Letter (NISO TR 3)
    def test_letterByLetterNISO3(self):
        items = EXPECTED_BY_LETTER[:]
        random.shuffle(items)
        results = []
        for term, saf, sortas in items:
            if saf != Saf.CUSTOM:
                sortas = SortAs.letterByLetterNISO3(term, saf, pad_digits=4)
            results.append((sortas, term, saf))
        results.sort()
        for i in range(len(EXPECTED_BY_LETTER)):
            sortas, aterm, asaf = results[i]
            xterm, xsaf = EXPECTED_BY_LETTER[i][:2]
            if DEBUG == 2:
                print("{:35} → {:35} : {}".format(aterm, sortas, xterm))
            self.assertEqual(aterm, xterm)
            self.assertEqual(asaf, xsaf)


EXPECTED_BY_WORD = [
    ("——on, Nicholas", Saf.CUSTOM, "!!-on nicholas"),
    ("<i>$$$ and sense</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("$10 a day", Saf.AUTO_NUMBER_ROMAN, None),
    ("$100 a year", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>$5000 reward</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("% of gain", Saf.AUTO_NUMBER_ROMAN, None),
    ("&amp; <i>see</i> ampersand", Saf.AUTO_NUMBER_ROMAN, None),
    ("***", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>¥ £ $ exchange tables</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("†mas star", Saf.AUTO_NUMBER_ROMAN, None),
    ("0.25 mm", Saf.AUTO_NUMBER, None),
    (".300 Vickers machine gun", Saf.AUTO_NUMBER_ROMAN, None),
    (".303-inch machine guns", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1 2 3 for Christmas</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1, 2, buckle my shoe</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1-4-5 boogie-woogie</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>2 kinetic sculptors</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("2-phase flow in turbines", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>2 x 2 = 5</i>", Saf.AUTO_NUMBER, None),
    ("3-D scale drawing", Saf.AUTO_NUMBER, None),
    ("<i>3 point 2 and what goes with it</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("3M Company", Saf.AUTO_NUMBER, None),
    ("3.1416 and all that", Saf.AUTO_NUMBER_ROMAN, None),
    ("007 James Bond", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>10 stars from the forties</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XVII</i><i> &amp; XVIII</i><i> siècles</i>",
        Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>17 days to better living</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XVII</i><i> siècle</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XX century encyclopedia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>20 funny stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>20 short stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("49 best short stories", Saf.AUTO_NUMBER_ROMAN, None),
    ("49<sub>Ca</sub> contamination", Saf.AUTO_NUMBER_ROMAN, None),
    ("100 [dollars] a year", Saf.AUTO_NUMBER_ROMAN, None),
    ("100 [percent] American", Saf.AUTO_NUMBER_ROMAN, None),
    ("100% American", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>600 new churches</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1066 and all that</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1984</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5,000- and 10,000-year star catalogs</i>", Saf.AUTO_NUMBER_ROMAN,
        None),
    ("<i>5000 años de historia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5000 Jahre Bier</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5.000 kilomètres dans le sud</i>", Saf.CUSTOM,
        "5000.0000 kilometres dans le sud"),
    ("A-1 steak sauce", Saf.AUTO_NUMBER_ROMAN, None),
    ("A-5 rocket", Saf.AUTO_NUMBER_ROMAN, None),
    ("A 99", Saf.AUTO_NUMBER_ROMAN, None),
    ("A and G motor vehicles", Saf.AUTO_NUMBER_ROMAN, None),
    ("A B C", Saf.AUTO_NUMBER_ROMAN, None),
    ("A [flat] sonata", Saf.AUTO_NUMBER_ROMAN, None),
    ("A la mode", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>A man</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>",
        Saf.AUTO_NUMBER_ROMAN, None),
    ("Aarhus", Saf.AUTO_NUMBER_ROMAN, None),
    ("Aastrøm, Jeppe", Saf.AUTO_NUMBER_ROMAN, None),
    ("Aav, Yrjö", Saf.AUTO_NUMBER_ROMAN, None),
    ("abacus", Saf.AUTO_NUMBER_ROMAN, None),
    ("Abalone", Saf.AUTO_NUMBER_ROMAN, None),
    ("A.B.C.", Saf.AUTO_NUMBER_ROMAN, None),
    ("abdomen", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ambassador hotel", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>...and so to bed (dots)</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>…and so to bed (ellipsis)</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Andersen, Hans Christian", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Antigone</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Astrom, Lara", Saf.AUTO_NUMBER_ROMAN, None),
    ("Åström, Margit", Saf.AUTO_NUMBER_ROMAN, None),
    ("B ... ch, A. (dots)", Saf.AUTO_NUMBER_ROMAN, None),
    ("B … ch, A. (ellipsis)", Saf.AUTO_NUMBER_ROMAN, None),
    ("B*** de B.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ba, Amadou", Saf.AUTO_NUMBER_ROMAN, None),
    ("Balzac, Honoré de", Saf.AUTO_NUMBER_ROMAN, None),
    ("B[aru]ch, A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (banknote)", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Bill Clinton: a life</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (ornithology)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (proposed law)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (request for payment)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (weapon)", Saf.AUTO_NUMBER_ROMAN, None),
    ("Byrum, John", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>C</i>", Saf.AUTO_NUMBER, None),
    ("C &amp; O canal", Saf.AUTO_NUMBER, None),
    ("C [sharp] ballad", Saf.AUTO_NUMBER, None),
    ("C-Vision", Saf.AUTO_NUMBER, None),
    ("<i>C Windows toolkit</i>", Saf.AUTO_NUMBER, None),
    ("C# ballad", Saf.AUTO_NUMBER, None),
    ("<i>C++ debugger</i>", Saf.AUTO_NUMBER, None),
    ("<i>C++ for expert systems</i>", Saf.AUTO_NUMBER, None),
    ("<i>C++ Views</i>", Saf.AUTO_NUMBER, None),
    ("<i>Cabaret</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Carmen</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("[Christ]mas greetings", Saf.AUTO_NUMBER_ROMAN, None),
    ("[Christ]mas star", Saf.AUTO_NUMBER_ROMAN, None),
    ("Cmdr. Smith", Saf.AUTO_NUMBER_ROMAN, None),
    ("CO<sub>2</sub> lasers", Saf.AUTO_NUMBER_ROMAN, None),
    ("Commander Brown", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Doctor Zhivago</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Doktor Faustus</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Double 0 Seven, James Bond</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("doxology", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Dr. Jekyll and Mr. Hyde</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("H<sub>2</sub>O", Saf.AUTO_NUMBER_ROMAN, None),
    ("H<sub>2</sub>SO<sub>4</sub>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Hamburg", Saf.AUTO_NUMBER_ROMAN, None),
    ("HO-scale", Saf.AUTO_NUMBER_ROMAN, None),
    ("John II, king of Aragon", Saf.AUTO_NUMBER_ROMAN, None),
    ("John II, pope", Saf.AUTO_NUMBER_ROMAN, None),
    ("John III, duke of Brabant", Saf.AUTO_NUMBER_ROMAN, None),
    ("John XXI, pope", Saf.AUTO_NUMBER_ROMAN, None),
    ("John family", Saf.AUTO_NUMBER_ROMAN, None),
    ("John the Baptist", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>M. Flip ignorait sa mort</i>", Saf.AUTO_NUMBER, None),
    ("<i>Man, A</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Man, The</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("M’Bow, Ahmadu", Saf.AUTO_NUMBER, None),
    # ("memory", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/Alzheimer’s disease", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/and psychoses", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/long-term", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/loss", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/of childhood", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/short-term", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mlle. Henriette", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mme. Pompadour", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Monsieur Verdoux</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mr. Adams", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Mrs. Miniver</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Muller, Arnold", Saf.AUTO_NUMBER_ROMAN, None),
    ("Müller, Fritz", Saf.AUTO_NUMBER_ROMAN, None),
    ("Muller, Greta", Saf.AUTO_NUMBER_ROMAN, None),
    ("N. E. Zenith Co.", Saf.AUTO_NUMBER_ROMAN, None),
    ("networks", Saf.AUTO_NUMBER_ROMAN, None),
    ("Nevves from America", Saf.AUTO_NUMBER_ROMAN, None),
    ("New, Agnes", Saf.AUTO_NUMBER_ROMAN, None),
    ("New Brunswick", Saf.AUTO_NUMBER_ROMAN, None),
    ("“New lamps for old”", Saf.AUTO_NUMBER_ROMAN, None),
    ("new moon", Saf.AUTO_NUMBER_ROMAN, None),
    ("New, Thomas", Saf.AUTO_NUMBER_ROMAN, None),
    ("New York", Saf.AUTO_NUMBER_ROMAN, None),
    ("New Zealand", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newark, DE", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newark, NJ", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newes from New England", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newfoundland", Saf.AUTO_NUMBER_ROMAN, None),
    ("news agencies", Saf.AUTO_NUMBER_ROMAN, None),
    ("news photography", Saf.AUTO_NUMBER_ROMAN, None),
    ("newsletters", Saf.AUTO_NUMBER_ROMAN, None),
    ("newspapers", Saf.AUTO_NUMBER_ROMAN, None),
    ("newsprint", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newton, Isaac", Saf.AUTO_NUMBER_ROMAN, None),
    ("newton (unit of force)", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newton’s rings", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Nineteen Eighty-four</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("No. 10, Downing Street", Saf.AUTO_NUMBER_ROMAN, None),
    ("No and yes", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>One hundred short stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Örne, Anders", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ornstein, Marvin", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ørsted, Hans Christian", Saf.AUTO_NUMBER_ROMAN, None),
    ("Peña, Carmen", Saf.AUTO_NUMBER_ROMAN, None),
    ("Penan, John", Saf.AUTO_NUMBER_ROMAN, None),
    ("Poe, E.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Poe[try]", Saf.AUTO_NUMBER_ROMAN, None),
    ("poetry", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>poetry in motion</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price &amp; Smith", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price &amp; Wilson", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price, A. E.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Route 45", Saf.AUTO_NUMBER_ROMAN, None),
    ("Route 66", Saf.AUTO_NUMBER_ROMAN, None),
    ("S.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("sailing boats", Saf.AUTO_NUMBER_ROMAN, None),
    ("Saint, P.K.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Sainte-Beuve, C.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Seton, Carl", Saf.AUTO_NUMBER_ROMAN, None),
    ("short stories", Saf.AUTO_NUMBER_ROMAN, None),
    ("Słonimski, Jan", Saf.AUTO_NUMBER_ROMAN, None),
    ("Slonimskii, Ivan", Saf.AUTO_NUMBER_ROMAN, None),
    ("Słownik geodezyjny", Saf.AUTO_NUMBER_ROMAN, None),
    ("Slowpoke", Saf.AUTO_NUMBER_ROMAN, None),
    ("SO<sub>4</sub><sup>-2</sup>", Saf.AUTO_NUMBER_ROMAN, None),
    ("SS. Pietro e Paolo", Saf.AUTO_NUMBER_ROMAN, None),
    ("SS (Schutzstaffel)", Saf.AUTO_NUMBER_ROMAN, None),
    ("St. Louis", Saf.AUTO_NUMBER_ROMAN, None),
    ("St. Moritz", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ste. Geneviève", Saf.AUTO_NUMBER_ROMAN, None),
    ("stearine", Saf.AUTO_NUMBER_ROMAN, None),
    ("System 7", Saf.AUTO_NUMBER_ROMAN, None),
    ("System 17", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The £100 wager</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 14th amendment</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 20th century encyclopedia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 30 years war</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 100 [pound] wager</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The man</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Two-stroke power units", Saf.AUTO_NUMBER_ROMAN, None),
    ("X-rays", Saf.AUTO_NUMBER, None),
    ("Xmas", Saf.AUTO_NUMBER_ROMAN, None),
    ("Xmas greetings", Saf.AUTO_NUMBER_ROMAN, None),
    ("XX rated movies", Saf.AUTO_NUMBER, None),
    ("YMCA", Saf.AUTO_NUMBER_ROMAN, None),
    ("Y.W.C.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zambia", Saf.AUTO_NUMBER_ROMAN, None),
    ("z.B.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zero-sum games", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zn", Saf.AUTO_NUMBER_ROMAN, None),
    ("ZnSO<sub>4</sub>", Saf.AUTO_NUMBER_ROMAN, None),
    ("zoos", Saf.AUTO_NUMBER_ROMAN, None),
    ]


EXPECTED_BY_LETTER = [
    ("——on, Nicholas", Saf.CUSTOM, "!!-on nicholas"),
    ("$10 a day", Saf.AUTO_NUMBER_ROMAN, None),
    ("$100 a year", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>$5000 reward</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>$$$ and sense</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("% of gain", Saf.AUTO_NUMBER_ROMAN, None),
    ("&amp; <i>see</i> ampersand", Saf.AUTO_NUMBER_ROMAN, None),
    ("***", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>¥ £ $ exchange tables</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("†mas star", Saf.AUTO_NUMBER_ROMAN, None),
    ("0.25 mm", Saf.AUTO_NUMBER, None),
    (".300 Vickers machine gun", Saf.AUTO_NUMBER_ROMAN, None),
    (".303-inch machine guns", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1 2 3 for Christmas</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1, 2, buckle my shoe</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1-4-5 boogie-woogie</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>2 kinetic sculptors</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("2-phase flow in turbines", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>2 x 2 = 5</i>", Saf.AUTO_NUMBER, None),
    ("3-D scale drawing", Saf.AUTO_NUMBER, None),
    ("3M Company", Saf.AUTO_NUMBER, None),
    ("<i>3 point 2 and what goes with it</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("3.1416 and all that", Saf.AUTO_NUMBER_ROMAN, None),
    ("007 James Bond", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>10 stars from the forties</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XVII</i><i> &amp; XVIII</i><i> siècles</i>",
        Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>17 days to better living</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XVII</i><i> siècle</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>XX century encyclopedia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>20 funny stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>20 short stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("49 best short stories", Saf.AUTO_NUMBER_ROMAN, None),
    ("49<sub>Ca</sub> contamination", Saf.AUTO_NUMBER_ROMAN, None),
    ("100% American", Saf.AUTO_NUMBER_ROMAN, None),
    ("100 [dollars] a year", Saf.AUTO_NUMBER_ROMAN, None),
    ("100 [percent] American", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>600 new churches</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1066 and all that</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>1984</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5,000- and 10,000-year star catalogs</i>", Saf.AUTO_NUMBER_ROMAN,
        None),
    ("<i>5000 años de historia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5000 Jahre Bier</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>5.000 kilomètres dans le sud</i>", Saf.CUSTOM,
        "5000.0000kilometresdanslesud"),
    ("A-1 steak sauce", Saf.AUTO_NUMBER_ROMAN, None),
    ("a<sup>2</sup> + b<sup>2</sup> = c<sup>2</sup>",
        Saf.AUTO_NUMBER_ROMAN, None),
    ("A-5 rocket", Saf.AUTO_NUMBER_ROMAN, None),
    ("A 99", Saf.AUTO_NUMBER_ROMAN, None),
    ("A and G motor vehicles", Saf.AUTO_NUMBER_ROMAN, None),
    ("Aarhus", Saf.AUTO_NUMBER_ROMAN, None),
    ("Aastrøm, Jeppe", Saf.AUTO_NUMBER_ROMAN, None),
    ("Aav, Yrjö", Saf.AUTO_NUMBER_ROMAN, None),
    ("abacus", Saf.AUTO_NUMBER_ROMAN, None),
    ("Abalone", Saf.AUTO_NUMBER_ROMAN, None),
    ("A B C", Saf.AUTO_NUMBER, None),
    ("A.B.C.", Saf.AUTO_NUMBER_ROMAN, None),
    ("abdomen", Saf.AUTO_NUMBER_ROMAN, None),
    ("A [flat] sonata", Saf.AUTO_NUMBER_ROMAN, None),
    ("A la mode", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>A man</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ambassador hotel", Saf.AUTO_NUMBER_ROMAN, None),
    ("Andersen, Hans Christian", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>...and so to bed (dots)</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>…and so to bed (ellipsis)</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Antigone</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Astrom, Lara", Saf.AUTO_NUMBER_ROMAN, None),
    ("Åström, Margit", Saf.AUTO_NUMBER_ROMAN, None),
    ("B*** de B.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ba, Amadou", Saf.AUTO_NUMBER_ROMAN, None),
    ("Balzac, Honoré de", Saf.AUTO_NUMBER_ROMAN, None),
    ("B[aru]ch, A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("B ... ch, A. (dots)", Saf.AUTO_NUMBER_ROMAN, None),
    ("B … ch, A. (ellipsis)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (banknote)", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Bill Clinton: a life</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (ornithology)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (proposed law)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (request for payment)", Saf.AUTO_NUMBER_ROMAN, None),
    ("bill (weapon)", Saf.AUTO_NUMBER_ROMAN, None),
    ("Byrum, John", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>C</i>", Saf.AUTO_NUMBER, None),
    ("C# ballad", Saf.AUTO_NUMBER, None),
    ("C &amp; O canal", Saf.AUTO_NUMBER, None),
    ("<i>C++ debugger</i>", Saf.AUTO_NUMBER, None),
    ("<i>C++ for expert systems</i>", Saf.AUTO_NUMBER, None),
    ("<i>C++ Views</i>", Saf.AUTO_NUMBER, None),
    ("<i>Cabaret</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Carmen</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("[Christ]mas greetings", Saf.AUTO_NUMBER_ROMAN, None),
    ("[Christ]mas star", Saf.AUTO_NUMBER_ROMAN, None),
    ("Cmdr. Smith", Saf.AUTO_NUMBER_ROMAN, None),
    ("CO<sub>2</sub> lasers", Saf.AUTO_NUMBER_ROMAN, None),
    ("Commander Brown", Saf.AUTO_NUMBER_ROMAN, None),
    ("C [sharp] ballad", Saf.AUTO_NUMBER, None),
    ("C-Vision", Saf.AUTO_NUMBER, None),
    ("<i>C Windows toolkit</i>", Saf.AUTO_NUMBER, None),
    ("<i>Doctor Zhivago</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Doktor Faustus</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Double 0 Seven, James Bond</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("doxology", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Dr. Jekyll and Mr. Hyde</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("H<sub>2</sub>O", Saf.AUTO_NUMBER_ROMAN, None),
    ("H<sub>2</sub>SO<sub>4</sub>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Hamburg", Saf.AUTO_NUMBER_ROMAN, None),
    ("HO-scale", Saf.AUTO_NUMBER_ROMAN, None),
    ("John II, king of Aragon", Saf.AUTO_NUMBER_ROMAN, None),
    ("John II, pope", Saf.AUTO_NUMBER_ROMAN, None),
    ("John III, duke of Brabant", Saf.AUTO_NUMBER_ROMAN, None),
    ("John XXI, pope", Saf.AUTO_NUMBER_ROMAN, None),
    ("John family", Saf.AUTO_NUMBER_ROMAN, None),
    ("John the Baptist", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Man, A</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Man, The</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("M’Bow, Ahmadu", Saf.AUTO_NUMBER, None),
    ("<i>M. Flip ignorait sa mort</i>", Saf.AUTO_NUMBER, None),
    # ("memory", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/Alzheimer’s disease", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/and psychoses", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/long-term", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/loss", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/of childhood", Saf.AUTO_NUMBER_ROMAN, None),
    # ("memory/short-term", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mlle. Henriette", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mme. Pompadour", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Monsieur Verdoux</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Mr. Adams", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Mrs. Miniver</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Muller, Arnold", Saf.AUTO_NUMBER_ROMAN, None),
    ("Müller, Fritz", Saf.AUTO_NUMBER_ROMAN, None),
    ("Muller, Greta", Saf.AUTO_NUMBER_ROMAN, None),
    ("networks", Saf.AUTO_NUMBER_ROMAN, None),
    ("Nevves from America", Saf.AUTO_NUMBER_ROMAN, None),
    ("New, Agnes", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newark, DE", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newark, NJ", Saf.AUTO_NUMBER_ROMAN, None),
    ("New Brunswick", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newes from New England", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newfoundland", Saf.AUTO_NUMBER_ROMAN, None),
    ("“New lamps for old”", Saf.AUTO_NUMBER_ROMAN, None),
    ("new moon", Saf.AUTO_NUMBER_ROMAN, None),
    ("news agencies", Saf.AUTO_NUMBER_ROMAN, None),
    ("newsletters", Saf.AUTO_NUMBER_ROMAN, None),
    ("newspapers", Saf.AUTO_NUMBER_ROMAN, None),
    ("news photography", Saf.AUTO_NUMBER_ROMAN, None),
    ("newsprint", Saf.AUTO_NUMBER_ROMAN, None),
    ("New, Thomas", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newton, Isaac", Saf.AUTO_NUMBER_ROMAN, None),
    ("Newton’s rings", Saf.AUTO_NUMBER_ROMAN, None),
    ("newton (unit of force)", Saf.AUTO_NUMBER_ROMAN, None),
    ("New York", Saf.AUTO_NUMBER_ROMAN, None),
    ("New Zealand", Saf.AUTO_NUMBER_ROMAN, None),
    ("N. E. Zenith Co.", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>Nineteen Eighty-four</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("No. 10, Downing Street", Saf.AUTO_NUMBER_ROMAN, None),
    ("No and yes", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>One hundred short stories</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Örne, Anders", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ornstein, Marvin", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ørsted, Hans Christian", Saf.AUTO_NUMBER_ROMAN, None),
    ("Peña, Carmen", Saf.AUTO_NUMBER_ROMAN, None),
    ("Penan, John", Saf.AUTO_NUMBER_ROMAN, None),
    ("Poe, E.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Poe[try]", Saf.AUTO_NUMBER_ROMAN, None),
    ("poetry", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>poetry in motion</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price &amp; Smith", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price &amp; Wilson", Saf.AUTO_NUMBER_ROMAN, None),
    ("Price, A. E.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Route 45", Saf.AUTO_NUMBER_ROMAN, None),
    ("Route 66", Saf.AUTO_NUMBER_ROMAN, None),
    ("S.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("sailing boats", Saf.AUTO_NUMBER_ROMAN, None),
    ("Sainte-Beuve, C.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Saint, P.K.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Seton, Carl", Saf.AUTO_NUMBER_ROMAN, None),
    ("short stories", Saf.AUTO_NUMBER_ROMAN, None),
    ("Slonimskii, Ivan", Saf.AUTO_NUMBER_ROMAN, None),
    ("Słonimski, Jan", Saf.AUTO_NUMBER_ROMAN, None),
    ("Słownik geodezyjny", Saf.AUTO_NUMBER_ROMAN, None),
    ("Slowpoke", Saf.AUTO_NUMBER_ROMAN, None),
    ("SO<sub>4</sub><sup>-2</sup>", Saf.AUTO_NUMBER_ROMAN, None),
    ("SS. Pietro e Paolo", Saf.AUTO_NUMBER_ROMAN, None),
    ("SS (Schutzstaffel)", Saf.AUTO_NUMBER_ROMAN, None),
    ("stearine", Saf.AUTO_NUMBER_ROMAN, None),
    ("Ste. Geneviève", Saf.AUTO_NUMBER_ROMAN, None),
    ("St. Louis", Saf.AUTO_NUMBER_ROMAN, None),
    ("St. Moritz", Saf.AUTO_NUMBER_ROMAN, None),
    ("System 7", Saf.AUTO_NUMBER_ROMAN, None),
    ("System 17", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The £100 wager</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 14th amendment</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 20th century encyclopedia</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 30 years war</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The 100 [pound] wager</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("<i>The man</i>", Saf.AUTO_NUMBER_ROMAN, None),
    ("Two-stroke power units", Saf.AUTO_NUMBER_ROMAN, None),
    ("Xmas", Saf.AUTO_NUMBER_ROMAN, None),
    ("Xmas greetings", Saf.AUTO_NUMBER_ROMAN, None),
    ("X-rays", Saf.AUTO_NUMBER, None),
    ("XX rated movies", Saf.AUTO_NUMBER, None),
    ("YMCA", Saf.AUTO_NUMBER_ROMAN, None),
    ("Y.W.C.A.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zambia", Saf.AUTO_NUMBER_ROMAN, None),
    ("z.B.", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zero-sum games", Saf.AUTO_NUMBER_ROMAN, None),
    ("Zn", Saf.AUTO_NUMBER_ROMAN, None),
    ("ZnSO<sub>4</sub>", Saf.AUTO_NUMBER_ROMAN, None),
    ("zoos", Saf.AUTO_NUMBER_ROMAN, None),
    ]

if __name__ == "__main__":
    unittest.main()
